# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Szymon Åopaciuk
email: szymon@lopaciuk.me
description: >
  I am a technology enthusiast and a computer science student at Loughorough University.
  This is my personal website and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: szymonlopaciuk
github_username:  szymonlopaciuk
sidebar_links:
  - title: About
    url: /index.html
  - title: Posts
    url: /posts.html
  - title: Portfolio
    url: /portfolio.html
  - title: GitHub
    url: https://github.com/szymonlopaciuk

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
